export default {
  CrimsonTextBold: "CrimsonText-Bold",
  CrimsonTextBoldItalic: "CrimsonText-BoldItalic",
  CrimsonTextItalic: "CrimsonText-Italic",
  CrimsonTextRegular: "CrimsonText-Regular",
  CrimsonTextSemiBold: "CrimsonText-SemiBold",
  CrimsonTextSemiBoldItalic: "CrimsonText-SemiBoldItalic",
  SpaceGroteskBold: "SpaceGrotesk-Bold",
  SpaceGroteskLight: "SpaceGrotesk-Light",
  SpaceGroteskMedium: "SpaceGrotesk-Medium",
  SpaceGroteskRegular: "SpaceGrotesk-Regular",
  SpaceGroteskSemiBold: "SpaceGrotesk-SemiBold",
  ArchivoBlack: "Archivo-Black",
  ArchivoBold: "Archivo-Bold",
  ArchivoExtraBold: "Archivo-ExtraBold",
  ArchivoLight: "Archivo-Light",
  ArchivoMedium: "Archivo-Medium",
  ArchivoRegular: "Archivo-Regular",
  ArchivoThin: "Archivo-Thin",
  SenBold: "Sen-Bold",
  SenExtraBold: "Sen-ExtraBold",
  SenMedium: "Sen-Medium",
  SenRegular: "Sen-Regular",
  SenSemiBold: "Sen-SemiBold",
};
