export default {
  ONBOADING: "OnBoading",
  HOME: "Home",
  DETAILS: "Details",
  LIST: "List",
  QUIZ: "QuizScreen",
  REWARDS: "Rewards",
  PASSPORT: "PassPortScreen",
  PLANET: "Planet",
  SPACE: "Space",
  PASSPORTLIST: "PassPortList",
  SIGNIN: "SignIn",
  GETSTARTED: "Get Started",
  SIGNUP: "SignUp",
  FORGOTPASSWORD: "ForgotPassword",
  VERIFYOTP: "VerifyOtp",
  NEWPASSWORD: "NewPassword",
  FINISH: "Finish",
};
