export const GET_EXOPLANETS_DATA_SUCCESS = "GET_EXOPLANETS_DATA_SUCCESS";
export const GET_EXOPLANETS_DATA_FAILED = "GET_EXOPLANETS_DATA_FAILED";
export const GET_QUIZ_DATA_SUCCESS = "GET_QUIZ_DATA_SUCCESS";
export const GET_QUIZ_DATA_FAILED = "GET_QUIZ_DATA_FAILED";
export const USER_DATA_SUCCESS = "USER_DATA_SUCCESS";
export const USER_SIGNIN_SUCCESS = "USER_SIGNIN_SUCCESS";
export const USER_SIGNIN_FAILED = "USER_SIGNIN_FAILED";
export const USER_SIGNUP_SUCCESS = "USER_SIGNUP_SUCCESS";
export const USER_SIGNUP_FAILED = "USER_SIGNUP_FAILED";
export const USER_FORGOT_PASSWORD_SUCCESS = "USER_FORGOT_PASSWORD_SUCCESS";
export const USER_FORGOT_PASSWORD_FAILED = "USER_FORGOT_PASSWORD_FAILED";
export const USER_OTP_VERIFY_SUCCESS = "USER_OTP_VERIFY_SUCCESS";
export const USER_OTP_VERIFY_FAILED = "USER_OTP_VERIFY_FAILED";
export const USER_RESEND_OTP_VERIFY_SUCCESS = "USER_RESEND_OTP_VERIFY_SUCCESS";
export const USER_RESEND_OTP_VERIFY_FAILED = "USER_RESEND_OTP_VERIFY_FAILED";
export const USER_CREATE_NEW_PASSWORD_SUCCESS =
  "USER_CREATE_NEW_PASSWORD_SUCCESS";
export const USER_CREATE_NEW_PASSWORD_FAILED =
  "USER_CREATE_NEW_PASSWORD_FAILED";
export const USER_INFO_GET_SUCCESS = "USER_INFO_GET_SUCCESS";
export const USER_INFO_GET_FAILED = "USER_INFO_GET_FAILED";
