export const GET_EXOPLANETS_DATA_SUCCESS = "GET_EXOPLANETS_DATA_SUCCESS";
export const GET_EXOPLANETS_DATA_FAILED = "GET_EXOPLANETS_DATA_FAILED";
export const GET_QUIZ_DATA_SUCCESS = "GET_QUIZ_DATA_SUCCESS";
export const GET_QUIZ_DATA_FAILED = "GET_QUIZ_DATA_FAILED";
